config:
    delay-between-messages: 1000
debug:
    enabled: false
zones:
    chat:
        enabled: true
        excluded-filters:
    signs:
        enabled: true
        excluded-filters:
            - duplicate-messages
            - leet
filters:
    duplicate-messages:
        default-level: 10
        priority: 5
    server-ip:
        default-level: 4
        priority: 1
    leet:
        default-level: 2
        priority: 4
    repeated-characters:
        default-level: 10
        priority: 2
        count: 5
    all-caps:
        default-level: 12
        priority: 3
        whitelist:
          - "I"
          - "PGM"
          - "OCN"
          - "MC"
          - ":D"
          - ":P"
          - "OK"
    profanity:
        default-level: 10
        priority: 5
        whitelist:
            - "snowball|snowballs"
        templates:
            tmp1:
                expression: "\\b%FIRST+%REST+|%FIRST+%REST+\\b"
                default: false
            tmp2:
                expression: "%WHOLE"
                default: true
            tmp3:
                expression: "\\b(%WHOLE)\\b"
                default: false
        words:
            "fuck":
                level: 30
            "wank":
                level: 15
            "dick":
                level: 20
            "cock":
                level: 22
            "penis":
                level: 20
            "shit":
                level: 10
            "piss":
                level: 7
            "skeet":
                level: 13
            "bitch":
                level: 15
            "tits":
                level: 12
            "titties":
                level: 12
            "pussy":
                level: 20
            "cunt":
                level: 25
            "twat":
                level: 12
            "clit":
                level: 15
            "ass|asshole|assface|badass":
                level: 10
                template: tmp3
            "nigger|nigga|niqqa":
                level: 30
            "faggot|queer":
                level: 25
            "slut":
                level: 15
            "anus|arse":
                level: 15
            "weed":
                level: 10
            "poon":
                level: 20
            "motherfuck":
                level: 30
            "mofo":
                level: 30
            "fag":
                level: 25
            "erection":
                level: 20
            "dildo":
                level: 13
            "anal":
                level: 15
                template: tmp3
            "bastard|basterd":
                level: 20
            "boner":
                level: 10
            "clit":
                level: 13
            "douche":
                level: 10
            "ejaculate":
                level: 20
            "goatse":
                level: 14
            "bukake":
                level: 14
            "masturbate|masterbate":
                level: 10
            "porn":
                level: 10
            "whore":
                level: 20
            "blowjob":
                level: 10
            "ejaculat":
                level: 20
